on:
  - push
jobs:
  build_readme:
    runs-on: ubuntu-latest
    name: Build README files
    steps:
      - uses: actions/checkout@v2
      - id: readme2tex
        uses: he7d3r/readme2tex-action@main
        with:
          user_name: '${{github.repository_owner}}'
          user_email: '${{github.actor}}@users.noreply.github.com'
